### ISSUE TITLE
Split - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tzmartin** [trueinteractions/tint2#122]
I'm getting a ``RangeError`` recursion error when clicking on a basic control use Container, Box or ImageWell within a Split view.
 
Test case:

```
require('Common');

var win = new Window();
var split = new Split();
var container = new Box();
var webview = new WebView();

win.appendChild(split);

container.left = container.right = container.top = container.bottom = 0;

webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = 'http://www.google.com';

split.left = split.right = split.top = split.bottom = 0;

split.appendChild(container);
split.appendChild(webview);

win.visible = true;
```

Click the left container:

![error](https://monosnap.com/file/H384vQ4jL0dA6YD9hSTIoVPWEoAgOE.png)

Any ideas?

**Comment by trevorlinton** [comment]
This is fixed in https://github.com/trueinteractions/tint2/commit/35bf64c9dc69d06335d2f277f93872b4ce1e1d5c

Let me know if you continue to have issues.  This will be included in version 2.1.12 that will be released later this evening.

**Comment by tzmartin** [comment]
Still receiving a RangeError exception on mouse events, when running the test case above.  I noticed a [commit](https://github.com/trueinteractions/tint2/commit/b12a17e7d39a18fe5aaefce05b7207ec2834513d) yesterday which includes the comment: *"The Split view will not respond mouse down or mouse up events."*  I compiled from head this morning, but it's still throwing an exception.  Any ideas?

**Comment by trevorlinton** [comment]
Split views have quickly become the most obnoxious part of all of the objective-c Apple framework/kits.  It handles mouse events in a very odd manner, most of the time a responder chain (if it does not handle a mouse event) will throw it up the chain to parent elements to manage and up its subclassed heirarchy incase any inheritance needs to handle it.  All NSView's in objective-c use this approach to event management.  In addition the NSSplitView does not implement any of OSX's auto-layout (as it in itself is a layout component).  Apple has more or less passively deprecated it as the component itself doesn't mesh with the ideals of how layout should be handled in the future.

So, what does this mean, NSSplitView, when it gets an un-terminated mouse event bubbling up will reforward it back to the child (much like a Window would, it affectively is a termination for events).  In Tint this causes the event to refire, and rebubble, then rinse and repeat until a stack overflow occurs.  The WebView (and other NSViews) don't have this issue because they terminate the events before the begin to bubble.  I'm utterly confused as to how to stop this behavior, Apple hasn't posted any documentation about it, hasn't deprecated NSSplitView and Xcode actually sort-of-rewrites the NSSplitView if you place it in an interface build to become auto layout, rather than a view... To top it off if you try and use auto layout the whole thing crashes.

I'll poke at this more, but be weary of split views, and if you can get away with it just use auto layout, e.g., if you need to place a box and webview on the same form but want to "lock" the box to the left:

```
require('Common');
var win = new Window();
var container = new Box();
var webview = new WebView();

container.left = 10;
container.width = 190; // set it at 200px
container.top = 0;
container.bottom = 10;

webview.left = 210; // set it at 210 pixels from left
webview.right = 0;
webview.top = 0;
webview.bottom = 0;

webview.location = 'http://www.google.com';

win.appendChild(container);
win.appendChild(webview);
win.visible = true;
```

Granted this doesn't fully fix the issue as the dimensions are resizable (unless you place another divider box between those two boxes and then resize the autolayout positions on mouse drag but thats kind of a pain).  

I've re-opened this issue and will look for a better implementation of SplitView that doesnt muck with the event handling.

Thanks!
Trevor

**Comment by trevorlinton** [comment]
Hi @tzmartin 

I have an update.  After around 77 hours (over the course of weeks) we've managed to hunt this issue down to its core.  The problem revolved around OSX' KVO observer capabilities.  I'm leaving this explanation less for you but for anyone else implementing Apple's runtime bridge, if you'd like to skip over the details all you need to know is its fully resolved and you shouldn't see any of the range errors happen again, the fix is on commit: https://github.com/trueinteractions/tint2/commit/69809a7931cc7b28a06ac8fc0fc7488d1d4c334a and will be in 2.1.14 to be released tomorrow.

The issue had to do with KVO.  KVO is apple's observer mechanism that's seemingly rarely used.  It allows any object in objective-c to observe when a property changes in any other object. It works by sub-classing the destination "observed" class at runtime (instead of compile time) and notifying the observer of changes by overloading selectors and posting the changes.  This has no effect at compile time because class pointers and id pointers are locked during the compile so dynamic sub-classing doesn't have an effect.

To illustrate this, think of inheritance.  In Apple's objective-c heirarchy for splitview you might have (as an example for Tint) NSView -> NSSplitView -> TintsSplitView.  When a mouse down is executed in objective-c the responder chain executes TintsSplitView's mouseDown selector. That selector then (unless it swallows the event), bubbles it up the heirarchy, in this instance it would execute NSSplitView's mouseDown so that if, say, the divider between two views is pressed the NSSplitView will handle this (TintSplitView's only role is to notify and execute the javascript attached by addEventListener), the NSSplitView will also notify up the heirarchy to NSView that the mouseDown was pressed, the NSView might do something like change the focused element, cursor, focus ring or a billion other things. 

KVO allows something to observe the mouseDown event, NSSplitView actually uses KVO to introspect into its sub-views to see what they are doing ( not really sure why, but its provable ).  In the instance where KVO is being used the heirarchy changes to:

 NSView -> NSSplitView -> TintsSplitView -> KVONSSplitView[idnum]_TintsSplitView

The KVO class that subclasses TintsSplitView acts as the "first responder", or the first to get the event.  It then propagates up the same way as before.  It has one dramatic design flaw, in that the classes above it will receive the base KVO class instead of their own during reflection (due to the fact that KVO operates during runtime, not at compile time).

This means that compiled Objective-C and Swift applications act exactly as they did before, without any necessary changes or even realizing that the sub-classing has occured.  However runtime methods which get the target pointer during the operation will see the KVO sub-class instead of themselves.  This is illustrated with the following example:

During the mouseDown for a non-KVO subclassed event you'll see this trace:
```javascript
self.getClass() [Class: NSView7134350]
self.getSuperclass() [Class: NSView]
self === super false
this.nativeViewClass  [Class: NSView7134350]
this.nativeViewClass === self.getClass() true
this.nativeViewClass === self.getSuperclass() false
```

However if KVO is being used by another object in the responder chain, you'll see this:
```javascript
self.getClass() [Class: NSKVONotifying_NSTableView7233373]
self.getSuperclass() [Class: NSTableView7233373]
self === super false
this.nativeViewClass  [Class: NSTableView7233373]
this.nativeViewClass === self.getClass() false
this.nativeViewClass === self.getSuperclass() true
```

The big difference is the class that Tint is using (or any runtime bridge) suddenly finds itself using a DIFFERENT class then it originally created. The class is actually a SUB-CLASS of itself, and a subclass that PROXIES all selectors back to the original class (thus acting the exact same and almost transparent).

This only becomes an issue when you want to call up the inheritance chain to notify classes that a mouseDown has happened.  

The stack overflow exhibited in this bug was happening due to the KVO class being executed, proxying and replacing itself with Tint's class, Tint seeing the KVO class instead of itself, requesting the next responder up the chain (Tint's own class) then calling mouseDown on it, with the same base class, and accidentally causing an infinite loop of recursive calls until the stack was exhausted. 

This also caused a few other minor bugs that were resolved as well! So that's also a plus. Moral of the story is runtime bridges have their own sneeky issues that we're glad are slowly being purged.  As I said earlier (and if you're still reading this), the bug is fixed and will be in 2.1.14.

Feel free to reopen if you have any additional RangeError or StackViolationError's thrown.

- Trevor

**Comment by tzmartin** [comment]
Thanks for this epic commit and for a good explanation on the Tint internals / KVO issue.  Definitely fixed.  I plan to dig more into the runtime bridge internals soon and hope to contribute back.  Right now I'm developing a product using Tint that I hope to release/share soon.  Really appreciate your work on this.
